# Generated by Django 3.2 on 2021-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
