# Generated by Django 3.2 on 2021-05-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
    ]
