# Generated by Django 3.2 on 2021-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='from_user',
            field=models.CharField(default='N', max_length=100),
            preserve_default=False,
        ),
    ]
